#!/bin/bash

VERSION_STRING=(`grep ELECTRUM_VERSION electrum_zcash/version.py`)
ELECTRUM_ZCASH_VERSION=${VERSION_STRING[2]}
ELECTRUM_ZCASH_VERSION=${ELECTRUM_ZCASH_VERSION#\'}
ELECTRUM_ZCASH_VERSION=${ELECTRUM_ZCASH_VERSION%\'}
export ELECTRUM_ZCASH_VERSION

APK_VERSION_STRING=(`grep APK_VERSION electrum_zcash/version.py`)
ELECTRUM_ZCASH_APK_VERSION=${APK_VERSION_STRING[2]}
ELECTRUM_ZCASH_APK_VERSION=${ELECTRUM_ZCASH_APK_VERSION#\'}
ELECTRUM_ZCASH_APK_VERSION=${ELECTRUM_ZCASH_APK_VERSION%\'}
export ELECTRUM_ZCASH_APK_VERSION

APK_VERSION_CODE_SCRIPT='./contrib/zcash/travis/calc_version_code.py'
export ELECTRUM_ZCASH_VERSION_CODE=`$APK_VERSION_CODE_SCRIPT`

# Check is release
SIMPLIFIED_VERSION_PATTERN="^([^A-Za-z]+).*"
if [[ ${ELECTRUM_ZCASH_VERSION} =~ ${SIMPLIFIED_VERSION_PATTERN} ]]; then
    if [[ ${BASH_REMATCH[1]} == ${ELECTRUM_ZCASH_VERSION} ]]; then
        export IS_RELEASE=y
    fi
fi
