#!/bin/bash

VERSION_STRING=(`grep ELECTRUM_VERSION electrum_zcash/version.py`)
ELECTRUM_ZCASH_VERSION=${VERSION_STRING[2]}
ELECTRUM_ZCASH_VERSION=${ELECTRUM_ZCASH_VERSION#\'}
ELECTRUM_ZCASH_VERSION=${ELECTRUM_ZCASH_VERSION%\'}
export ELECTRUM_ZCASH_VERSION

APK_VERSION_STRING=(`grep APK_VERSION electrum_zcash/version.py`)
ELECTRUM_ZCASH_APK_VERSION=${APK_VERSION_STRING[2]}
ELECTRUM_ZCASH_APK_VERSION=${ELECTRUM_ZCASH_APK_VERSION#\'}
ELECTRUM_ZCASH_APK_VERSION=${ELECTRUM_ZCASH_APK_VERSION%\'}
export ELECTRUM_ZCASH_APK_VERSION
